export {default as StyledBanner} from './banner'
export {default as StyledFeatures} from './features'
export {default as StyledFeaturesList} from './featuresList'
export {default as StyledPrograms} from './programs'
export {default as StyledProducts} from './products'
export {default as StyledContact} from './contact'
export {default as StyledGetStarted} from './getStarted'