backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "Blog Post"
    folder: content/blog
    create: true
    slug: "{{slug}}"
    media_folder: "static/img"
    public_folder: "/img"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: image,
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - label: Home
    name: home
    files:
      - label: Banner
        name: 'banner'
        file: "src/home/banner.md"
        public_folder: "../img"
        fields:
          - label: Services
            name: services
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }