backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "Blog Post"
    folder: content/blog
    create: true
    slug: "{{slug}}"
    media_folder: "static/img"
    public_folder: "/img"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: image,
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - label: index-page
    name: index
    files:
      - label: banner
        name: banner
        file: "content/home/banner.json"
        public_folder: "../img/"
        fields:
          - label: banner
            name: banner
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Description, name: description }
              - { label: Image, name: image, widget: image }
      - label: about
        name: about
        file: "content/home/about.json"
        public_folder: "../img/"
        fields:
          - { label: heading, name: heading }
          - { label: Image, name: image, widget: image }
          - { label: sub heading 1, name: subHeadingOne }
          - { label: sub heading 2, name: subHeadingTwo }
          - { label: paragraph, name: paragraph }
          - { label: Right Image One, name: image, widget: image }
          - { label: Right Image Two, name: image, widget: image }
      - label: services
        name: services
        file: "content/home/services.json"
        public_folder: "../img/"
        fields:
          - { label: heading, name: heading }
          - { label: sub heading, name: subHeading }
          - { label: image, name: image, widget: image }
          - { label: paragraph, name: paragraph }
          - label: services
            name: services
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
