backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "Blog Post"
    folder: content/blog
    create: true
    slug: "{{slug}}"
    media_folder: "static/img"
    public_folder: "/img"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: image,
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - label: Home
    name: home
    files:
      - label: Banner
        name: homeBanner
        file: "src/data/home/banner.md"
        public_folder: "../img"
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Services
        name: homeServices
        file: "src/data/home/services.md"
        public_folder: "../img"
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Services
            name: services
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Clients
        name: homeClients
        file: "src/data/home/clients.md"
        public_folder: "../img"
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Clients
            name: clients
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Works
        name: homeWorks
        file: "src/data/home/works.md"
        public_folder: "../img"
        fields:
          - { label: Title, name: title }
          - label: Works
            name: works
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Description, name: description }
              - {
                  name: type,
                  label: Type,
                  widget: "select",
                  options: ["casestudy", "website"],
                }
              - { label: Link, name: link }
              - { label: Image, name: image, widget: image }
      - label: SEO
        name: homeSeo
        file: "src/data/home/seo.md"
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
